name: Release

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Labels
        id: labels
        run: |
          echo "is_merged=${{ github.event.pull_request.merged }}"
          echo "labels=${{ github.event.pull_request.labels }}"
